name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup the build env
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            podman \
            qemu-user-static \
            pkg-config \
            libdbus-1-dev \
            binutils-aarch64-linux-gnu
          cargo binstall --no-confirm cross

      - name: Build for x86_64 linux gnu
        run: |
          cargo build --release
          cp target/release/bzmenu bzmenu-x86_64-linux-gnu
          strip bzmenu-x86_64-linux-gnu

      - name: Build for aarch64 linux gnu
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target aarch64-unknown-linux-gnu --release
          cp target/aarch64-unknown-linux-gnu/release/bzmenu bzmenu-aarch64-linux-gnu
          aarch64-linux-gnu-strip bzmenu-aarch64-linux-gnu

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bzmenu-*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-') }}
